import { useMemo, useState } from 'react'
import { useTrackRecord } from '../hooks/useAlerts'
import { tradingViewUrl } from '../lib/tradingview'
import { cellCls, rowCls, tableWrapCls, theadCls } from '../lib/ui'
import { BENCHMARK_LABELS, CATEGORY_LABELS, type TrackRecordEntry } from '../types'
import { MarketBadge } from './AlertTable'
import Badge from './ui/Badge'
import Chip from './ui/Chip'
import SectionHeading from './ui/SectionHeading'
import Tabs, { type TabItem } from './ui/Tabs'

function Pct({ v, dp = 2 }: { v: number | null | undefined; dp?: number }) {
  if (v === null || v === undefined) return <span className="text-faint">—</span>
  return (
    <span className={v >= 0 ? 'text-up' : 'text-down'}>
      {v >= 0 ? '+' : ''}
      {v.toFixed(dp)}%
    </span>
  )
}

const mean = (xs: number[]) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0)
const num = (v: number | null | undefined) => (v === null || v === undefined ? NaN : v)

// Entries younger than this have no meaningful result yet — shown as "pending"
// and excluded from the hit-rate/average chips.
const SEASONED_DAYS = 2
const seasoned = (e: TrackRecordEntry) => e.days_held >= SEASONED_DAYS && e.excess_pct !== null

// Compact rule names for the per-rule breakdown chips (full names in tooltip)
const RULE_SHORT: Record<string, string> = {
  price_sma200: 'Daily SMA200',
  sma50_sma200: 'Golden cross',
  price_sma200_weekly: '200-week',
}

// Same ticker+rule fired again within this window → tag the later one "re-entry"
const REFIRE_DAYS = 14
function refireIds(entries: TrackRecordEntry[]): Set<string> {
  const out = new Set<string>()
  const day = 86400000
  for (const e of entries) {
    const t = new Date(e.entry_date).getTime()
    if (entries.some((o) => o.ticker === e.ticker && o.rule === e.rule &&
        o.entry_date < e.entry_date && t - new Date(o.entry_date).getTime() <= REFIRE_DAYS * day))
      out.add(e.id)
  }
  return out
}

type SortKey = 'excess_pct' | 'stock_return_pct' | 'entry_date' | 'days_held' | 'ticker'
type ResultFilter = 'all' | 'beat' | 'lag'

const RESULT_ITEMS: TabItem<ResultFilter>[] = [
  { value: 'all', label: 'All', tone: 'info' },
  { value: 'beat', label: 'Beat', tone: 'up' },
  { value: 'lag', label: 'Lagging', tone: 'down' },
]

// numeric sort with NaN/null always pushed to the bottom regardless of direction
function cmp(a: number, b: number, dir: 1 | -1): number {
  const an = Number.isNaN(a), bn = Number.isNaN(b)
  if (an && bn) return 0
  if (an) return 1
  if (bn) return -1
  return (a - b) * dir
}

function SortHeader({
  label, col, sort, setSort, className = '',
}: {
  label: string
  col: SortKey
  sort: { key: SortKey; dir: 1 | -1 }
  setSort: (s: { key: SortKey; dir: 1 | -1 }) => void
  className?: string
}) {
  const active = sort.key === col
  return (
    <th
      className={`${cellCls} cursor-pointer select-none hover:text-ink ${className}`}
      onClick={() => setSort({ key: col, dir: active && sort.dir === -1 ? 1 : -1 })}
    >
      {label}
      <span className={`ml-1 ${active ? 'text-accent' : 'text-transparent'}`}>
        {active && sort.dir === 1 ? '▲' : '▼'}
      </span>
    </th>
  )
}

export default function TrackRecordPage() {
  const { track, error } = useTrackRecord()
  const [category, setCategory] = useState('all')
  const [result, setResult] = useState<ResultFilter>('all')
  const [sort, setSort] = useState<{ key: SortKey; dir: 1 | -1 }>({ key: 'excess_pct', dir: -1 })

  const entries = track?.entries ?? []

  const categoryItems: TabItem<string>[] = useMemo(() => {
    const present = [...new Set(entries.map((e) => e.category))]
    const known = Object.keys(CATEGORY_LABELS).filter((c) => present.includes(c))
    const rest = present.filter((c) => !known.includes(c))
    return [{ value: 'all', label: 'All categories', tone: 'info' as const },
            ...[...known, ...rest].map((c) => ({ value: c, label: CATEGORY_LABELS[c] ?? c }))]
  }, [entries])

  const refires = useMemo(() => refireIds(entries), [entries])

  const rows = useMemo(() => {
    const filtered = entries.filter(
      (e) =>
        (category === 'all' || e.category === category) &&
        (result === 'all' ||
          (result === 'beat' ? e.success === true && seasoned(e) : e.success === false && seasoned(e))),
    )
    const keyed = (e: TrackRecordEntry) =>
      sort.key === 'ticker' ? e.ticker : sort.key === 'entry_date' ? e.entry_date : num(e[sort.key])
    return [...filtered].sort((a, b) => {
      const ka = keyed(a), kb = keyed(b)
      if (typeof ka === 'string' || typeof kb === 'string')
        return String(ka).localeCompare(String(kb)) * sort.dir
      return cmp(ka as number, kb as number, sort.dir)
    })
  }, [entries, category, result, sort])

  if (error) {
    return (
      <p className="border border-dashed border-hair bg-raised px-4 py-8 text-center text-sm text-muted">
        No track record yet — it is generated by the daily scan once BUY alerts start firing.
      </p>
    )
  }
  if (!track) return <p className="py-8 text-center text-muted">Loading…</p>

  const scored = entries.filter(seasoned)
  const pending = entries.length - scored.length
  const beat = scored.filter((e) => e.success === true).length
  const hitRate = scored.length ? (beat / scored.length) * 100 : 0
  const avgExcess = mean(scored.map((e) => e.excess_pct as number))
  const avgReturn = mean(scored.map((e) => e.stock_return_pct as number))
  const avgDays = mean(scored.map((e) => e.days_held))
  // seasoned only, to match every other headline stat's honesty rule
  const targetsHit = scored.filter((e) => e.target_reached === true).length
  const ranked = [...scored].sort((a, b) => (b.excess_pct as number) - (a.excess_pct as number))
  const best = ranked[0]
  const worst = ranked[ranked.length - 1]

  // Per-rule breakdown of the seasoned set: the headline hit-rate blends a
  // high-volume noisy rule (daily SMA200) with rarer, better ones — showing
  // each rule's own record stops the blended number being misread.
  const byRule = Object.entries(
    scored.reduce<Record<string, TrackRecordEntry[]>>((acc, e) => {
      ;(acc[e.category] ??= []).push(e)
      return acc
    }, {}),
  )
    .map(([cat, rows]) => ({
      cat,
      n: rows.length,
      beatPct: (100 * rows.filter((e) => e.success === true).length) / rows.length,
      avgExcess: mean(rows.map((e) => e.excess_pct as number)),
    }))
    .sort((a, b) => b.n - a.n)

  return (
    <section className="space-y-4">
      <SectionHeading
        title="Alert track record — did the buys beat their market?"
        right={
          <span className="text-xs text-muted">
            {entries.length} tracked · each vs its market index · bar {track.bar_date}
          </span>
        }
      />

      <div className="flex flex-wrap gap-2.5">
        <Chip label="Tracked" value={pending > 0 ? `${entries.length} (${pending} pending)` : entries.length} />
        <Chip label="Beat benchmark" value={`${hitRate.toFixed(0)}%`}
              tone={hitRate >= 50 ? 'up' : 'down'}
              title={`${beat} of ${scored.length} seasoned entries (held ≥${SEASONED_DAYS}d)`} />
        <Chip label="Avg excess" value={`${avgExcess >= 0 ? '+' : ''}${avgExcess.toFixed(2)}pp`}
              tone={avgExcess >= 0 ? 'up' : 'down'} />
        <Chip label="Avg return" value={`${avgReturn >= 0 ? '+' : ''}${avgReturn.toFixed(1)}%`}
              tone={avgReturn >= 0 ? 'up' : 'down'} />
        <Chip label="Avg held" value={`${avgDays.toFixed(0)}d`} />
        {targetsHit > 0 && (
          <Chip label="🎯 targets hit" value={targetsHit}
                title="Entries whose price reached the analyst mean target from their alert day" />
        )}
        {best && (
          <Chip label="Best" value={`${best.ticker} ${best.excess_pct! >= 0 ? '+' : ''}${best.excess_pct!.toFixed(1)}`}
                tone={best.excess_pct! >= 0 ? 'up' : 'down'} />
        )}
        {worst && worst !== best && (
          <Chip label="Worst" value={`${worst.ticker} ${worst.excess_pct! >= 0 ? '+' : ''}${worst.excess_pct!.toFixed(1)}`}
                tone={worst.excess_pct! < 0 ? 'down' : 'up'} />
        )}
      </div>

      {byRule.length > 1 && (
        <div className="flex flex-wrap items-center gap-2.5">
          <span className="text-xs text-muted">By rule</span>
          {byRule.map(({ cat, n, beatPct, avgExcess }) => (
            <Chip
              key={cat}
              label={RULE_SHORT[cat] ?? cat}
              value={`${beatPct.toFixed(0)}% · ${avgExcess >= 0 ? '+' : ''}${avgExcess.toFixed(1)}pp (${n})`}
              tone={avgExcess >= 0 ? 'up' : 'down'}
              title={`${CATEGORY_LABELS[cat] ?? cat} — ${n} seasoned entries: beat benchmark ${beatPct.toFixed(0)}%, avg excess ${avgExcess >= 0 ? '+' : ''}${avgExcess.toFixed(2)}pp`}
            />
          ))}
        </div>
      )}

      <div className="flex flex-wrap items-center gap-3">
        <Tabs items={categoryItems} active={category} onChange={setCategory} size="sm" />
        <Tabs items={RESULT_ITEMS} active={result} onChange={setResult} size="sm" />
      </div>

      {rows.length > 0 ? (
        <div className={tableWrapCls}>
          <table className="w-full text-left text-[13px]">
            <thead className={theadCls}>
              <tr>
                <SortHeader label="Ticker" col="ticker" sort={sort} setSort={setSort} />
                <th className={cellCls}>Category</th>
                <th className={cellCls}>Benchmark</th>
                <SortHeader label="Entry" col="entry_date" sort={sort} setSort={setSort} />
                <th className={`${cellCls} text-right`}>Entry px</th>
                <th className={`${cellCls} text-right`}>Current</th>
                <SortHeader label="Return" col="stock_return_pct" sort={sort} setSort={setSort} className="text-right" />
                <th className={`${cellCls} text-right`}>Bench</th>
                <SortHeader label="Excess" col="excess_pct" sort={sort} setSort={setSort} className="text-right" />
                <SortHeader label="Held" col="days_held" sort={sort} setSort={setSort} className="text-right" />
                <th className={cellCls}>Result</th>
              </tr>
            </thead>
            <tbody className="tnum divide-y divide-hair">
              {rows.map((e) => (
                <tr key={e.id} className={rowCls}>
                  <td className={cellCls}>
                    <a href={tradingViewUrl(e.ticker)} target="_blank" rel="noreferrer"
                       className="font-semibold text-info hover:underline">{e.ticker} ↗</a>
                    <MarketBadge market={e.market} />
                    {refires.has(e.id) && (
                      <span className="ml-1.5 text-[10px] text-muted"
                            title={`Same signal re-fired within ${REFIRE_DAYS} days — possible whipsaw`}>
                        ↩ re-entry
                      </span>
                    )}
                  </td>
                  <td className={`${cellCls} text-xs text-muted`}>{CATEGORY_LABELS[e.category] ?? e.category}</td>
                  <td className={`${cellCls} text-xs text-muted`}>
                    {e.benchmark ? `vs ${BENCHMARK_LABELS[e.benchmark] ?? e.benchmark}` : '—'}
                  </td>
                  <td className={`${cellCls} text-muted`}>{e.entry_date}</td>
                  <td className={`${cellCls} text-right text-ink-2`}>
                    {e.entry_price >= 10 ? e.entry_price.toFixed(2) : e.entry_price.toFixed(4)}
                  </td>
                  <td className={`${cellCls} text-right text-ink-2`}>
                    {e.last_price !== null
                      ? (e.last_price >= 10 ? e.last_price.toFixed(2) : e.last_price.toFixed(4))
                      : <span className="text-faint">n/a</span>}
                    {e.target_reached && (
                      <span className="ml-1 cursor-help"
                            title={`Analyst mean target reached (${e.target_mean})`}>🎯</span>
                    )}
                  </td>
                  <td className={`${cellCls} text-right`}><Pct v={e.stock_return_pct} /></td>
                  <td className={`${cellCls} text-right`}><Pct v={e.bench_return_pct} /></td>
                  <td className={`${cellCls} text-right font-medium`}><Pct v={e.excess_pct} /></td>
                  <td className={`${cellCls} text-right text-muted`}>
                    {e.days_held}d{e.status === 'matured' ? <span className="ml-1 text-faint" title="Evaluation window complete">·done</span> : ''}
                  </td>
                  <td className={cellCls}>
                    {e.success === null ? (
                      <span className="text-faint">—</span>
                    ) : !seasoned(e) ? (
                      <Badge tone="neutral" title={`Held <${SEASONED_DAYS} days — too new to judge`}>
                        pending
                      </Badge>
                    ) : e.success ? (
                      <Badge tone="up">✓ beat</Badge>
                    ) : (
                      <Badge tone="down">✗ lag</Badge>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        <p className="border border-dashed border-hair bg-raised px-4 py-8 text-center text-sm text-muted">
          No tracked alerts match this filter.
        </p>
      )}

      <p className="text-xs text-muted">
        Every <span className="text-ink-2">BUY</span> alert is captured at its alert-day close and
        tracked forward. <span className="text-ink-2">Excess</span> = the stock's return since the
        alert minus its own market index over the same window (US → S&P 500, DE → DAX, BIST → BIST 100
        — same currency as the stock, so no FX distortion); a signal <span className="text-ink-2">beats</span>
        its market when excess is positive. Entries held under {SEASONED_DAYS} days show{' '}
        <span className="text-ink-2">pending</span> and are excluded from the headline stats;
        🎯 marks a price that reached the analyst mean target from its alert day; ↩ marks a
        signal that re-fired within {REFIRE_DAYS} days (possible whipsaw). Entries evaluate over
        ~180 days, then freeze (·done).
        Prices are split- but not dividend-adjusted (TradingView parity), so long-window returns on
        high-yield names read slightly low. Informational, not investment advice.
      </p>
    </section>
  )
}
