import { useMemo, useState } from 'react'
import { useTrackRecord } from '../hooks/useAlerts'
import { tradingViewUrl } from '../lib/tradingview'
import { cellCls, rowCls, tableWrapCls, theadCls } from '../lib/ui'
import { BENCHMARK_LABELS, CATEGORY_LABELS, type TrackRecordEntry } from '../types'
import { MarketBadge } from './AlertTable'
import Badge from './ui/Badge'
import Chip from './ui/Chip'
import SectionHeading from './ui/SectionHeading'
import Tabs, { type TabItem } from './ui/Tabs'

function Pct({ v, dp = 2 }: { v: number | null | undefined; dp?: number }) {
  if (v === null || v === undefined) return <span className="text-faint">—</span>
  return (
    <span className={v >= 0 ? 'text-up' : 'text-down'}>
      {v >= 0 ? '+' : ''}
      {v.toFixed(dp)}%
    </span>
  )
}

const mean = (xs: number[]) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0)
const num = (v: number | null | undefined) => (v === null || v === undefined ? NaN : v)

type SortKey = 'excess_pct' | 'stock_return_pct' | 'entry_date' | 'days_held' | 'ticker'
type ResultFilter = 'all' | 'beat' | 'lag'

const RESULT_ITEMS: TabItem<ResultFilter>[] = [
  { value: 'all', label: 'All', tone: 'info' },
  { value: 'beat', label: 'Beat', tone: 'up' },
  { value: 'lag', label: 'Lagging', tone: 'down' },
]

// numeric sort with NaN/null always pushed to the bottom regardless of direction
function cmp(a: number, b: number, dir: 1 | -1): number {
  const an = Number.isNaN(a), bn = Number.isNaN(b)
  if (an && bn) return 0
  if (an) return 1
  if (bn) return -1
  return (a - b) * dir
}

function SortHeader({
  label, col, sort, setSort, className = '',
}: {
  label: string
  col: SortKey
  sort: { key: SortKey; dir: 1 | -1 }
  setSort: (s: { key: SortKey; dir: 1 | -1 }) => void
  className?: string
}) {
  const active = sort.key === col
  return (
    <th
      className={`${cellCls} cursor-pointer select-none hover:text-ink ${className}`}
      onClick={() => setSort({ key: col, dir: active && sort.dir === -1 ? 1 : -1 })}
    >
      {label}
      <span className={`ml-1 ${active ? 'text-accent' : 'text-transparent'}`}>
        {active && sort.dir === 1 ? '▲' : '▼'}
      </span>
    </th>
  )
}

export default function TrackRecordPage() {
  const { track, error } = useTrackRecord()
  const [category, setCategory] = useState('all')
  const [result, setResult] = useState<ResultFilter>('all')
  const [sort, setSort] = useState<{ key: SortKey; dir: 1 | -1 }>({ key: 'excess_pct', dir: -1 })

  const entries = track?.entries ?? []

  const categoryItems: TabItem<string>[] = useMemo(() => {
    const present = [...new Set(entries.map((e) => e.category))]
    const known = Object.keys(CATEGORY_LABELS).filter((c) => present.includes(c))
    const rest = present.filter((c) => !known.includes(c))
    return [{ value: 'all', label: 'All categories', tone: 'info' as const },
            ...[...known, ...rest].map((c) => ({ value: c, label: CATEGORY_LABELS[c] ?? c }))]
  }, [entries])

  const rows = useMemo(() => {
    const filtered = entries.filter(
      (e) =>
        (category === 'all' || e.category === category) &&
        (result === 'all' || (result === 'beat' ? e.success === true : e.success === false)),
    )
    const keyed = (e: TrackRecordEntry) =>
      sort.key === 'ticker' ? e.ticker : sort.key === 'entry_date' ? e.entry_date : num(e[sort.key])
    return [...filtered].sort((a, b) => {
      const ka = keyed(a), kb = keyed(b)
      if (typeof ka === 'string' || typeof kb === 'string')
        return String(ka).localeCompare(String(kb)) * sort.dir
      return cmp(ka as number, kb as number, sort.dir)
    })
  }, [entries, category, result, sort])

  if (error) {
    return (
      <p className="border border-dashed border-hair bg-raised px-4 py-8 text-center text-sm text-muted">
        No track record yet — it is generated by the daily scan once BUY alerts start firing.
      </p>
    )
  }
  if (!track) return <p className="py-8 text-center text-muted">Loading…</p>

  const scored = entries.filter((e) => e.excess_pct !== null)
  const beat = entries.filter((e) => e.success === true).length
  const hitRate = scored.length ? (beat / scored.length) * 100 : 0
  const avgExcess = mean(scored.map((e) => e.excess_pct as number))
  const avgReturn = mean(entries.filter((e) => e.stock_return_pct !== null).map((e) => e.stock_return_pct as number))
  const avgDays = mean(entries.map((e) => e.days_held))
  const ranked = [...scored].sort((a, b) => (b.excess_pct as number) - (a.excess_pct as number))
  const best = ranked[0]
  const worst = ranked[ranked.length - 1]

  return (
    <section className="space-y-4">
      <SectionHeading
        title="Alert track record — did the buys beat their market?"
        right={
          <span className="text-xs text-muted">
            {entries.length} tracked · each vs its market index · bar {track.bar_date}
          </span>
        }
      />

      <div className="flex flex-wrap gap-2.5">
        <Chip label="Tracked" value={entries.length} />
        <Chip label="Beat benchmark" value={`${hitRate.toFixed(0)}%`}
              tone={hitRate >= 50 ? 'up' : 'down'} />
        <Chip label="Avg excess" value={`${avgExcess >= 0 ? '+' : ''}${avgExcess.toFixed(2)}pp`}
              tone={avgExcess >= 0 ? 'up' : 'down'} />
        <Chip label="Avg return" value={`${avgReturn >= 0 ? '+' : ''}${avgReturn.toFixed(1)}%`}
              tone={avgReturn >= 0 ? 'up' : 'down'} />
        <Chip label="Avg held" value={`${avgDays.toFixed(0)}d`} />
        {best && (
          <Chip label="Best" value={`${best.ticker} ${best.excess_pct! >= 0 ? '+' : ''}${best.excess_pct!.toFixed(1)}`}
                tone="up" />
        )}
        {worst && worst !== best && (
          <Chip label="Worst" value={`${worst.ticker} ${worst.excess_pct! >= 0 ? '+' : ''}${worst.excess_pct!.toFixed(1)}`}
                tone={worst.excess_pct! < 0 ? 'down' : 'up'} />
        )}
      </div>

      <div className="flex flex-wrap items-center gap-3">
        <Tabs items={categoryItems} active={category} onChange={setCategory} size="sm" />
        <Tabs items={RESULT_ITEMS} active={result} onChange={setResult} size="sm" />
      </div>

      {rows.length > 0 ? (
        <div className={tableWrapCls}>
          <table className="w-full text-left text-[13px]">
            <thead className={theadCls}>
              <tr>
                <SortHeader label="Ticker" col="ticker" sort={sort} setSort={setSort} />
                <th className={cellCls}>Category</th>
                <th className={cellCls}>Benchmark</th>
                <SortHeader label="Entry" col="entry_date" sort={sort} setSort={setSort} />
                <th className={`${cellCls} text-right`}>Entry px</th>
                <th className={`${cellCls} text-right`}>Current</th>
                <SortHeader label="Return" col="stock_return_pct" sort={sort} setSort={setSort} className="text-right" />
                <th className={`${cellCls} text-right`}>Bench</th>
                <SortHeader label="Excess" col="excess_pct" sort={sort} setSort={setSort} className="text-right" />
                <SortHeader label="Held" col="days_held" sort={sort} setSort={setSort} className="text-right" />
                <th className={cellCls}>Result</th>
              </tr>
            </thead>
            <tbody className="tnum divide-y divide-hair">
              {rows.map((e) => (
                <tr key={e.id} className={rowCls}>
                  <td className={cellCls}>
                    <a href={tradingViewUrl(e.ticker)} target="_blank" rel="noreferrer"
                       className="font-semibold text-info hover:underline">{e.ticker} ↗</a>
                    <MarketBadge market={e.market} />
                  </td>
                  <td className={`${cellCls} text-xs text-muted`}>{CATEGORY_LABELS[e.category] ?? e.category}</td>
                  <td className={`${cellCls} text-xs text-muted`}>
                    {e.benchmark ? `vs ${BENCHMARK_LABELS[e.benchmark] ?? e.benchmark}` : '—'}
                  </td>
                  <td className={`${cellCls} text-muted`}>{e.entry_date}</td>
                  <td className={`${cellCls} text-right text-ink-2`}>
                    {e.entry_price >= 10 ? e.entry_price.toFixed(2) : e.entry_price.toFixed(4)}
                  </td>
                  <td className={`${cellCls} text-right text-ink-2`}>
                    {e.last_price !== null
                      ? (e.last_price >= 10 ? e.last_price.toFixed(2) : e.last_price.toFixed(4))
                      : <span className="text-faint">n/a</span>}
                  </td>
                  <td className={`${cellCls} text-right`}><Pct v={e.stock_return_pct} /></td>
                  <td className={`${cellCls} text-right`}><Pct v={e.bench_return_pct} /></td>
                  <td className={`${cellCls} text-right font-medium`}><Pct v={e.excess_pct} /></td>
                  <td className={`${cellCls} text-right text-muted`}>
                    {e.days_held}d{e.status === 'matured' ? <span className="ml-1 text-faint" title="Evaluation window complete">·done</span> : ''}
                  </td>
                  <td className={cellCls}>
                    {e.success === null ? (
                      <span className="text-faint">—</span>
                    ) : e.success ? (
                      <Badge tone="up">✓ beat</Badge>
                    ) : (
                      <Badge tone="down">✗ lag</Badge>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        <p className="border border-dashed border-hair bg-raised px-4 py-8 text-center text-sm text-muted">
          No tracked alerts match this filter.
        </p>
      )}

      <p className="text-xs text-muted">
        Every <span className="text-ink-2">BUY</span> alert is captured at its alert-day close and
        tracked forward. <span className="text-ink-2">Excess</span> = the stock's return since the
        alert minus its own market index over the same window (US → S&P 500, DE → DAX, BIST → BIST 100
        — same currency as the stock, so no FX distortion); a signal <span className="text-ink-2">beats</span>
        its market when excess is positive. Entries evaluate over ~180 days, then freeze (·done).
        Prices are split- but not dividend-adjusted (TradingView parity), so long-window returns on
        high-yield names read slightly low. Informational, not investment advice.
      </p>
    </section>
  )
}
